# Data Cleaning

Before conducting the analysis, several data preparation steps were performed to ensure data quality and consistency:

- Checked for missing values across all datasets
- Converted variables to appropriate data types (e.g., timestamps)
- Removed duplicate records
- Merged the web activity dataset with the experiment assignment and process step datasets
- Verified that each `visit_id` corresponds to a single `client_id`
- Validated that each visit belongs to only one experiment group (Control or Test)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_web_pt1 = pd.read_csv("https://raw.githubusercontent.com/ngocha2811/ab-testing-vanguard-digital-journey/refs/heads/main/data/raw/df_final_web_data_pt_1.csv")
df_web_pt2 = pd.read_csv("https://raw.githubusercontent.com/ngocha2811/ab-testing-vanguard-digital-journey/refs/heads/main/data/raw/df_final_web_data_pt_2.csv")

df_web = pd.concat([df_web_pt1, df_web_pt2], ignore_index=True)

df_demo = pd.read_csv("https://raw.githubusercontent.com/ngocha2811/ab-testing-vanguard-digital-journey/refs/heads/main/data/raw/df_final_demo.csv")
df_variation = pd.read_csv("https://raw.githubusercontent.com/ngocha2811/ab-testing-vanguard-digital-journey/refs/heads/main/data/raw/df_final_experiment_clients.csv")

In [3]:
display(df_web)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [4]:
df_web.dtypes

client_id        int64
visitor_id      object
visit_id        object
process_step    object
date_time       object
dtype: object

In [6]:
### Check for Anomalies
## Nulls
## Duplicates
## Anomalies

In [5]:
df_demo.isna().sum()

client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

In [6]:
df_web.isna().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [7]:
df_variation.isna().sum()

client_id        0
Variation    20109
dtype: int64

In [8]:
### Cleaning df_demo

df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [9]:
for col in df_demo.select_dtypes(include="number").columns:
    col_median = df_demo[col].median()
    df_demo[col].fillna(col_median, inplace=True)

/var/folders/z1/hpkmqfl54717zbjq651n7__40000gn/T/ipykernel_74784/224476067.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_demo[col].fillna(col_median, inplace=True)

In [10]:
df_demo["gendr"].mode()[0]

df_demo["gendr"].fillna(df_demo["gendr"].mode()[0], inplace=True)

/var/folders/z1/hpkmqfl54717zbjq651n7__40000gn/T/ipykernel_74784/1084669219.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_demo["gendr"].fillna(df_demo["gendr"].mode()[0], inplace=True)

In [11]:
df_demo.isna().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
dtype: int64

In [12]:
### Cleaning df_variation

df_variation.dropna(inplace=True)

In [13]:
df_web

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [14]:
df_web = pd.merge(left = df_web, right = df_variation, on = "client_id", how="inner")

In [15]:
df_web.dropna(inplace=True)

In [16]:
df_web

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
321304,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
321305,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
321306,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
321307,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
321308,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [17]:
### Duplicates

df_web.duplicated().sum()

df_web.drop_duplicates(inplace=True)

In [18]:
df_demo.duplicated().sum()

np.int64(0)

In [19]:
df_variation.duplicated().sum()

np.int64(0)

In [20]:
df_variation

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

In [21]:
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [23]:
client_per_visit = df_web.groupby("visit_id").agg({"client_id":"nunique"}).sort_values(by="client_id", ascending=False)
client_per_visit

                              client_id
visit_id
604261403_30358583476_150602          2
546449552_41982066121_512526          2
91270599_44898025227_352270           2
573613158_55382966010_784228          2
266579786_60182148749_455296          2
...                                 ...
402755493_51028899321_725434          1
402761208_50271707233_643672          1
402769497_11473729081_534170          1
402773862_85265008842_4745            1
999988789_76411676596_272843          1

[69205 rows x 1 columns]

In [24]:
visits_to_drop = client_per_visit[client_per_visit["client_id"]>1].index
visits_to_drop

Index(['604261403_30358583476_150602', '546449552_41982066121_512526',
       '91270599_44898025227_352270', '573613158_55382966010_784228',
       '266579786_60182148749_455296', '779501243_85245437003_850255',
       '147972690_17593388107_595987', '771591919_12450338520_978128',
       '702805857_89266038491_741382', '666301065_4786889521_478087',
       ...
       '221426169_83991952715_486292', '318531813_18355633226_707500',
       '303794948_29817973580_353053', '5754057_82753076210_545592',
       '458140827_71657566359_314943', '758669476_6749287141_803743',
       '241263020_54751959590_84526', '546971488_81140698228_42567',
       '286863145_33626706776_314019', '348926422_78818342369_380761'],
      dtype='object', name='visit_id', length=242)

In [25]:
df_web = df_web[~df_web["visit_id"].isin(visits_to_drop)]

In [26]:
df_web.sort_values(by=["client_id", "visit_id" ,"date_time"], inplace=True)
df_web

/var/folders/z1/hpkmqfl54717zbjq651n7__40000gn/T/ipykernel_74784/1812948362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web.sort_values(by=["client_id", "visit_id" ,"date_time"], inplace=True)

,client_id,visitor_id,visit_id,process_step,date_time,Variation
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test
...,...,...,...,...,...,...
276143,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test
105350,9999729,604429154_69247391147,99583652_41711450505_426179,start,2017-04-05 13:40:49,Test
105349,9999729,604429154_69247391147,99583652_41711450505_426179,step_1,2017-04-05 13:41:04,Test
244975,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test
244974,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test