In [96]:
import pandas as pd
import scipy.stats as st
from statsmodels.stats.proportion import proportions_ztest
import numpy as np

In [68]:
df_web_pt1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_1.txt")
df_web_pt2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_2.txt")

df_web = pd.concat([df_web_pt1, df_web_pt2], ignore_index=True)

df_demo = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_demo.txt")
df_variation = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_experiment_clients.txt")

In [6]:
display(df_web)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [147]:
df_web.dtypes

client_id                 int64
visitor_id               object
visit_id                 object
process_step             object
date_time                object
Variation                object
process_step_encoded      int64
step_diff               float64
dtype: object

In [ ]:
### Check for Anomalies
## Nulls
## Duplicates
## Anomalies

In [17]:
df_demo.isna().sum()

client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

In [24]:
df_web.isna().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [25]:
df_variation.isna().sum()

client_id        0
Variation    20109
dtype: int64

In [10]:
### Cleaning df_demo

df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [69]:
for col in df_demo.select_dtypes(include="number").columns:
    col_median = df_demo[col].median()
    df_demo[col].fillna(col_median, inplace=True)

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\224476067.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_demo[col].fillna(col_median, inplace=True)

In [70]:
df_demo["gendr"].mode()[0]

df_demo["gendr"].fillna(df_demo["gendr"].mode()[0], inplace=True)

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\1084669219.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_demo["gendr"].fillna(df_demo["gendr"].mode()[0], inplace=True)

In [71]:
df_demo.isna().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
dtype: int64

In [72]:
### Cleaning df_variation

df_variation.dropna(inplace=True)

In [30]:
df_web

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [73]:
df_web = pd.merge(left = df_web, right = df_variation, on = "client_id", how="inner")

In [74]:
df_web

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
321304,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
321305,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
321306,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
321307,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
321308,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [75]:
### Duplicates

df_web.duplicated().sum()

df_web.drop_duplicates(inplace=True)

In [76]:
df_demo.duplicated().sum()

np.int64(0)

In [77]:
df_variation.duplicated().sum()

np.int64(0)

In [78]:
## Anomalies

df_web

,client_id,visitor_id,visit_id,process_step,date_time,Variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
321304,1574008,117364417_77840596075,528720790_71583064618_169151,start,2017-05-06 23:43:27,Test
321305,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:57:17,Control
321306,2908510,814969699_90652851448,562606085_36368381773_92090,step_2,2017-05-10 22:56:31,Control
321307,2908510,814969699_90652851448,562606085_36368381773_92090,step_1,2017-05-10 22:56:23,Control
321308,2908510,814969699_90652851448,562606085_36368381773_92090,start,2017-05-10 22:56:20,Control

In [79]:
## Visit_id corresponds to a single Client_id

client_per_visit = df_web.groupby("visit_id").agg({"client_id":"nunique"}).sort_values(by="client_id", ascending=False)
client_per_visit

                              client_id
visit_id
604261403_30358583476_150602          2
546449552_41982066121_512526          2
91270599_44898025227_352270           2
573613158_55382966010_784228          2
266579786_60182148749_455296          2
...                                 ...
402755493_51028899321_725434          1
402761208_50271707233_643672          1
402769497_11473729081_534170          1
402773862_85265008842_4745            1
999988789_76411676596_272843          1

[69205 rows x 1 columns]

In [80]:
visits_to_drop = client_per_visit[client_per_visit["client_id"]>1].index
visits_to_drop

Index(['604261403_30358583476_150602', '546449552_41982066121_512526',
       '91270599_44898025227_352270', '573613158_55382966010_784228',
       '266579786_60182148749_455296', '779501243_85245437003_850255',
       '147972690_17593388107_595987', '771591919_12450338520_978128',
       '702805857_89266038491_741382', '666301065_4786889521_478087',
       ...
       '221426169_83991952715_486292', '318531813_18355633226_707500',
       '303794948_29817973580_353053', '5754057_82753076210_545592',
       '458140827_71657566359_314943', '758669476_6749287141_803743',
       '241263020_54751959590_84526', '546971488_81140698228_42567',
       '286863145_33626706776_314019', '348926422_78818342369_380761'],
      dtype='object', name='visit_id', length=242)

In [81]:
df_web = df_web[~df_web["visit_id"].isin(visits_to_drop)]

In [82]:
df_web.sort_values(by=["client_id", "visit_id" ,"date_time"], inplace=True)
df_web

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\1812948362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web.sort_values(by=["client_id", "visit_id" ,"date_time"], inplace=True)

,client_id,visitor_id,visit_id,process_step,date_time,Variation
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test
...,...,...,...,...,...,...
276143,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test
105350,9999729,604429154_69247391147,99583652_41711450505_426179,start,2017-04-05 13:40:49,Test
105349,9999729,604429154_69247391147,99583652_41711450505_426179,step_1,2017-04-05 13:41:04,Test
244975,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test
244974,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test

In [83]:
### Every visit_id is mapped to a single Variation (either Test or Control, never both)

df_web.groupby("visit_id")["Variation"].nunique().reset_index().sort_values(by="Variation", ascending=False)

                           visit_id  Variation
0      100012776_37918976071_457913          1
45981  700355178_31623928130_462227          1
45967  700190990_11171081628_520439          1
45968   70020077_40688951654_976127          1
45969   700211866_9445656730_286696          1
...                             ...        ...
22992  402170104_12902080536_238460          1
22993  402186373_60129242148_182347          1
22994  402203822_54194913691_872242          1
22995  402234626_19272441400_686123          1
68962  999988789_76411676596_272843          1

[68963 rows x 2 columns]

### Completion Rate

In [85]:
### Completion Rate

#---> #visit completed/#total_visits

df_web["process_step_encoded"] = df_web["process_step"].map({"start":0,
                                                             "step_1":1,
                                                             "step_2":2,
                                                             "step_3":3,
                                                             "confirm":4})

df_web

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\2156644500.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web["process_step_encoded"] = df_web["process_step"].map({"start":0,

,client_id,visitor_id,visit_id,process_step,date_time,Variation,process_step_encoded
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,1
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,3
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,4
...,...,...,...,...,...,...,...
276143,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,4
105350,9999729,604429154_69247391147,99583652_41711450505_426179,start,2017-04-05 13:40:49,Test,0
105349,9999729,604429154_69247391147,99583652_41711450505_426179,step_1,2017-04-05 13:41:04,Test,1
244975,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0
244974,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,1

In [89]:
df_cr = df_web.groupby(["Variation","visit_id"])["process_step_encoded"].max().reset_index()
df_cr["completed"] = df_cr["process_step_encoded"] == 4
df_cr

      Variation                      visit_id  process_step_encoded  completed
0       Control  100030127_47967100085_936361                     0      False
1       Control  100037962_47432393712_705583                     1      False
2       Control  100057941_88477660212_944512                     3      False
3       Control   10006594_66157970412_679648                     4       True
4       Control  100071743_53464757454_616703                     0      False
...         ...                           ...                   ...        ...
68958      Test  999960019_60838685252_926860                     2      False
68959      Test  999971096_28827267783_236076                     4       True
68960      Test  999976049_95772503197_182554                     4       True
68961      Test  999984454_18731538378_781808                     4       True
68962      Test  999988789_76411676596_272843                     2      False

[68963 rows x 4 columns]

In [93]:
# H0: Completion and Variation are independent
# H1: Completion and Variation are dependent

#sl = 0.05

crosstab_var_c = pd.crosstab(df_cr["Variation"], df_cr["completed"])

p_value = st.chi2_contingency(crosstab_var_c)[1]
p_value

np.float64(6.449123953301238e-116)

In [ ]:
"""We have gathered enough evidence to reject the null hypothesis, concluding that Completion and Variation are dependent"""

In [97]:
crosstab_var_c

completed  False  True
Variation
Control    16123  15892
Test       15390  21558

In [100]:
#We could also run a PROPORTION_ZTEST

# H0: p_Confirm Control = p_Confirm Test
# H1: p_Confirm Control != p_Confirm Test

#sl = 0.05


#number of times clients have reached "confirm step"
count = np.array([15892, 21558])

#number of observations (success + failures)
nobs = np.array([(16123+15892), (15390+21558)])

proportions_ztest(count, nobs)

(np.float64(-22.89336786565089), np.float64(5.40966446522552e-116))

In [101]:
count

array([15892, 21558])

In [121]:
#H0: p_Confirm Test - p_Confirm Control >= 5%
#H1: p_Confirm Test - p_Confirm Control < 5%

#sl=0.05

count = np.array([21558, 15892])

nobs = np.array([(15390+21558), (16123+15892)])

proportions_ztest(count, nobs, value=0.05, alternative="smaller")

(np.float64(9.74779514504426), np.float64(1.0))

In [105]:
print("Completion Rate for Test: ",21558/(15390+21558))
print("Completion Rate for Control: ", 15892/(16123+15892))

Completion Rate for Test:  0.5834686586554076
Completion Rate for Control:  0.49639231610182727

### Error Rate

Considering Visits with Errors, if the user goes from a later step to an earlier one.

Error_rate = #visits_errors/#total_visits

In [129]:
df_web["step_diff"] = df_web.groupby("visit_id")["process_step_encoded"].diff()

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\1334373782.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web["step_diff"] = df_web.groupby("visit_id")["process_step_encoded"].diff()

In [139]:
df_error = df_web.groupby(["Variation","visit_id"])["step_diff"].min().reset_index()
df_error["is_error"] = df_error["step_diff"] < 0
df_error

      Variation                      visit_id  step_diff  is_error
0       Control  100030127_47967100085_936361        NaN     False
1       Control  100037962_47432393712_705583       -1.0      True
2       Control  100057941_88477660212_944512       -2.0      True
3       Control   10006594_66157970412_679648       -1.0      True
4       Control  100071743_53464757454_616703        NaN     False
...         ...                           ...        ...       ...
68958      Test  999960019_60838685252_926860       -2.0      True
68959      Test  999971096_28827267783_236076        0.0     False
68960      Test  999976049_95772503197_182554        0.0     False
68961      Test  999984454_18731538378_781808        1.0     False
68962      Test  999988789_76411676596_272843       -1.0      True

[68963 rows x 4 columns]

In [140]:
# H0: Variation and is_Error are independent
# H1: Variation and is_Error are dependent

# sl=5%

crosstab = pd.crosstab(df_error["Variation"], df_error["is_error"])
crosstab

is_error   False  True
Variation
Control    25540   6475
Test       27034   9914

In [141]:
print("The Error Ratio on Control is ", (6475/(6475+25540)))
print("The Error Ratio on Test is ", (9914/(9914+27034)))

The Error Ratio on Control is  0.20224894580665312
The Error Ratio on Test is  0.2683230486088557

In [142]:
st.chi2_contingency(crosstab)

Chi2ContingencyResult(statistic=np.float64(412.96797709429654), pvalue=np.float64(8.280941097183503e-92), dof=1, expected_freq=array([[24406.66168815,  7608.33831185],
       [28167.33831185,  8780.66168815]]))

In [ ]:
"""With such a low p_value, we can reject the null hypothesis"""

In [143]:
## PROPORTION Z TEST

# H0: p_Error Test = p_Error Control
# H1: p_Error Test != p_Error Control

#sl = 5%

count = np.array([9914, 6475])

nobs = np.array([(9914+27034), (6475+25540)])


proportions_ztest(count = count , nobs=nobs)

(np.float64(20.33058288094039), np.float64(6.897823090048048e-92))

In [144]:
# H0: p_Error Test >= p_Error Control
# H1: p_Error Test < p_Error Control

#sl = 5%

count = np.array([9914, 6475])

nobs = np.array([(9914+27034), (6475+25540)])


proportions_ztest(count = count , nobs=nobs, alternative="smaller")

(np.float64(20.33058288094039), np.float64(1.0))

### Time spent per each Step

To calculate time spent per each step, we are going to calculate the consecutive differences on date_time per visit_id
 - DataFrame is sorted by visit_id and date_time

In [150]:
df_web["date_time"] = pd.to_datetime(df_web["date_time"])

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\2402432093.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web["date_time"] = pd.to_datetime(df_web["date_time"])

In [155]:
df_web["time_diff"] = df_web.groupby("visit_id")["date_time"].diff()
df_web["time_diff"] = df_web["time_diff"].dt.total_seconds()

C:\Users\frede\AppData\Local\Temp\ipykernel_2192\925962122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web["time_diff"] = df_web.groupby("visit_id")["date_time"].diff()
C:\Users\frede\AppData\Local\Temp\ipykernel_2192\925962122.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_web["time_diff"] = df_web["time_diff"].dt.total_seconds()

In [156]:
df_web

,client_id,visitor_id,visit_id,process_step,date_time,Variation,process_step_encoded,step_diff,time_diff
70803,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,Test,0,NaN,NaN
70802,555,402506806_56087378777,637149525_38041617439_716659,step_1,2017-04-15 12:58:03,Test,1,1.0,7.0
70801,555,402506806_56087378777,637149525_38041617439_716659,step_2,2017-04-15 12:58:35,Test,2,1.0,32.0
70800,555,402506806_56087378777,637149525_38041617439_716659,step_3,2017-04-15 13:00:14,Test,3,1.0,99.0
70799,555,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test,4,1.0,20.0
...,...,...,...,...,...,...,...,...,...
276143,9999729,834634258_21862004160,870243567_56915814033_814203,confirm,2017-05-08 16:09:40,Test,4,1.0,21.0
105350,9999729,604429154_69247391147,99583652_41711450505_426179,start,2017-04-05 13:40:49,Test,0,NaN,NaN
105349,9999729,604429154_69247391147,99583652_41711450505_426179,step_1,2017-04-05 13:41:04,Test,1,1.0,15.0
244975,9999832,145538019_54444341400,472154369_16714624241_585315,start,2017-05-16 16:46:03,Test,0,NaN,NaN
244974,9999832,145538019_54444341400,472154369_16714624241_585315,step_1,2017-05-16 16:46:11,Test,1,1.0,8.0

In [158]:
df_web.groupby(["Variation", "process_step"])["time_diff"].mean().reset_index()

  Variation process_step   time_diff
0   Control      confirm  130.524927
1   Control        start  174.181926
2   Control       step_1   43.342610
3   Control       step_2   38.895414
4   Control       step_3   94.365122
5      Test      confirm  129.685373
6      Test        start  151.287686
7      Test       step_1   37.833715
8      Test       step_2   48.442835
9      Test       step_3   97.570591

In [168]:
# H0: mu step_1 Test = mu step_1 Control
# H1: mu step_1 Test != mu step_1 Control

#sl = 5%

test_s1 = df_web[(df_web["Variation"]=="Test") & (df_web["process_step"]=="step_1")]["time_diff"].dropna()
control_s1 = df_web[(df_web["Variation"]=="Control") & (df_web["process_step"]=="step_1")]["time_diff"].dropna()

st.ttest_ind(test_s1, control_s1)

TtestResult(statistic=np.float64(-7.039401499818836), pvalue=np.float64(1.9491417822082123e-12), df=np.float64(67027.0))

In [169]:
# H0: mu confirm Test = mu confirm Control
# H1: mu confirm Test != mu confirm Control

#sl = 5%

test_s1 = df_web[(df_web["Variation"]=="Test") & (df_web["process_step"]=="confirm")]["time_diff"].dropna()
control_s1 = df_web[(df_web["Variation"]=="Control") & (df_web["process_step"]=="confirm")]["time_diff"].dropna()

st.ttest_ind(test_s1, control_s1)

TtestResult(statistic=np.float64(-0.36368740601330624), pvalue=np.float64(0.7160934552380795), df=np.float64(38319.0))

In [ ]:
#Next

## Identifying more problems and remove them
#### Removing outliers (time per step)
#### Should we focus on "Primary Clients" --> should i include clients that very rarely uses Vanguard Investment Process?
#### ...

In [171]:
df_demo["logons_6_mnth"].mean()

np.float64(5.566627483748531)

In [172]:
df_demo[df_demo["logons_6_mnth"]<2]

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
50508,1206758,13.0,166.0,43.5,M,3.0,144800.87,1.0,1.0
50520,5041923,9.0,111.0,34.5,F,2.0,37823.38,1.0,1.0
50529,6367363,8.0,103.0,32.5,U,2.0,21728.80,1.0,1.0
50534,4293314,20.0,250.0,46.0,F,2.0,26273.38,1.0,1.0
50537,6108929,6.0,74.0,55.5,F,2.0,23813.24,1.0,1.0
...,...,...,...,...,...,...,...,...,...
70572,197859,9.0,112.0,52.5,F,2.0,128650.26,1.0,1.0
70585,1331944,23.0,285.0,60.0,M,2.0,34168.90,1.0,1.0
70594,7953988,10.0,120.0,32.5,M,2.0,41473.34,1.0,1.0
70595,1196936,15.0,184.0,45.5,F,2.0,482000.12,1.0,1.0
70600,6746156,8.0,106.0,32.0,F,2.0,19019.55,1.0,1.0